'use client';
// Market-level symbol TradeSignal requests have been removed.
// This card is now purely informational and does not trigger any manual signal generation.

import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { ExternalLink } from 'lucide-react';
import Link from 'next/link';

interface RequestSymbolSignalProps {
  symbol: string;
}

export function RequestSymbolSignal({ symbol }: RequestSymbolSignalProps) {
  return (
    <Card>
      <CardHeader>
        <div className="flex items-center justify-between">
          <div>
            <CardTitle>AI Trade Signals</CardTitle>
            <CardDescription>
              {symbol} is evaluated automatically as part of the Active Model Universe. Manual
              TradeSignal requests are no longer supported.
            </CardDescription>
          </div>
          <Link
            href="/tradesignals"
            className="text-sm text-muted-foreground hover:text-foreground flex items-center gap-1"
          >
            View Signals
            <ExternalLink className="h-3 w-3" />
          </Link>
        </div>
      </CardHeader>
      <CardContent>
        <p className="text-sm text-muted-foreground">
          All signals are generated by the AI engine from the approved Active Model Universe.
          To review outcomes, use the Signals and Performance views rather than requesting
          one-off trades.
        </p>
      </CardContent>
    </Card>
  );
}
