/**
 * Shared types for backtest engine modules (V3, V3.5, V4, V4.1)
 */

export interface BacktestParams {
  symbol: string;
  engineType: 'DAYTRADER' | 'SWING' | 'INVESTOR';
  engineVersion: 'V3' | 'V3_5' | 'V4' | 'V4_1';
  timeframe: string; // '5m' | '15m' | '1H' | '4H' | '1D' | '1W' | '1M'
  ohlc: OHLCBar[];
  initialBalance: number; // e.g. 100000
  horizonDays: number;
}

export interface OHLCBar {
  timestamp: number; // Unix ms
  open: number;
  high: number;
  low: number;
  close: number;
  volume: number;
}

export interface TradeRecord {
  entryTime: number;      // Unix timestamp (ms)
  exitTime: number;       // Unix timestamp (ms)
  entryPrice: number;
  exitPrice: number;
  direction: 'long' | 'short';
  rMultiple: number;      // e.g. +2.5 or -1.0
  win: boolean;
  pnl: number;            // dollar P&L
}

export interface BacktestStats {
  totalReturnPct: number;
  maxDrawdownPct: number;
  winRatePct: number;
  avgR: number;
  tradeCount: number;
  bestTradeR: number;
  worstTradeR: number;
}

export interface EquityPoint {
  time: number;    // Unix timestamp (ms)
  value: number;   // Portfolio equity
}

export interface BacktestResult {
  stats: BacktestStats;
  equityCurve: EquityPoint[];
  trades: TradeRecord[];
}

/**
 * Position currently held during backtest
 */
export interface Position {
  entryTime: number;
  entryPrice: number;
  stopLoss: number;
  takeProfit: number;
  direction: 'long' | 'short';
  size: number; // number of shares
}

/**
 * Technical indicators calculated from OHLC data
 */
export interface TechnicalIndicators {
  ema9?: number;
  ema21?: number;
  ema50?: number;
  ema200?: number;
  atr?: number;
  rsi?: number;
  macd?: {
    macd: number;
    signal: number;
    histogram: number;
  };
  volume_ma?: number;
}

/**
 * Entry signal generated by engine logic
 */
export interface EntrySignal {
  type: 'long' | 'short' | null;
  confidence: number; // 0-100
  stopLoss: number;
  takeProfit: number;
}
