"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { CheckCircle2, ArrowRight } from "lucide-react";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";

interface HowWeTradeModalProps {
  trigger: React.ReactNode;
}

export function HowWeTradeModal({ trigger }: HowWeTradeModalProps) {
  const [performanceHref, setPerformanceHref] = useState("/signup");

  useEffect(() => {
    // Check auth status to determine where to route user
    const checkAuth = async () => {
      try {
        const res = await fetch("/api/access/status", { cache: "no-store" });
        const data = await res.json();
        if (data.is_logged_in) {
          setPerformanceHref("/dashboard/performance/live");
        } else {
          setPerformanceHref("/signup");
        }
      } catch {
        setPerformanceHref("/signup");
      }
    };
    checkAuth();
  }, []);

  return (
    <Dialog>
      <DialogTrigger asChild>{trigger}</DialogTrigger>
      <DialogContent className="max-w-2xl sm:max-w-3xl">
        <DialogHeader>
          <DialogTitle className="text-2xl sm:text-3xl font-semibold tracking-tight">
            How Marild Trades (Live & Transparent)
          </DialogTitle>
          <DialogDescription className="text-base text-muted-foreground">
            A step-by-step look at our live trading logic and portfolio rules.
          </DialogDescription>
        </DialogHeader>

        <div className="mt-4 space-y-6 max-h-[60vh] overflow-y-auto pr-1">
          {/* Section A */}
          <section className="space-y-2">
            <div className="flex items-center gap-2">
              <CheckCircle2 className="h-5 w-5 text-emerald-500 animate-[fadeInUp_0.5s_ease-out_forwards]" />
              <h3 className="text-lg font-semibold">Signal Generation</h3>
            </div>
            <p className="text-sm sm:text-base text-muted-foreground leading-relaxed">
              Marild scans 50+ approved tickers every hour during market hours. Every signal is generated by the same rules-based logic, with no discretionary overrides and no user-by-user customization. This keeps the process auditable, repeatable, and free from behavioral bias.
            </p>
          </section>

          {/* Section B */}
          <section className="space-y-3">
            <div className="flex items-center gap-2">
              <CheckCircle2 className="h-5 w-5 text-emerald-500 animate-[fadeInUp_0.6s_ease-out_forwards]" />
              <h3 className="text-lg font-semibold">Risk Management</h3>
            </div>
            <ul className="list-disc pl-5 space-y-1 text-sm sm:text-base text-muted-foreground">
              <li>Single model portfolio with <span className="font-medium">$100,000</span> starting capital.</li>
              <li>Fixed <span className="font-medium">0.75%</span> risk per trade for consistent position sizing.</li>
              <li>Position size capped at 25% of portfolio to avoid outsized single-trade exposure.</li>
              <li>Maximum <span className="font-medium">10 concurrent positions</span> and 80% max allocation.</li>
              <li>Signals may be skipped when the portfolio is fully allocated or risk limits are reached.</li>
            </ul>
            <div className="mt-2 rounded-md border-l-4 border-emerald-500 bg-emerald-500/5 px-4 py-3 text-sm text-muted-foreground">
              <span className="font-semibold text-foreground">We do NOT assume infinite capital.</span>
              <span> The model portfolio is constrained just like a real trading account.</span>
            </div>
          </section>

          {/* Section C */}
          <section className="space-y-2">
            <div className="flex items-center gap-2">
              <CheckCircle2 className="h-5 w-5 text-emerald-500 animate-[fadeInUp_0.7s_ease-out_forwards]" />
              <h3 className="text-lg font-semibold">Portfolio Execution</h3>
            </div>
            <p className="text-sm sm:text-base text-muted-foreground leading-relaxed">
              Signals are processed in chronological order. For a given ticker, entries do not overlap—the existing position must be closed before a new one is opened. Positions are held based on market structure and exit criteria (take-profit, stop-loss, or trailing stop), with no arbitrary time limits.
            </p>
          </section>

          {/* Section D */}
          <section className="space-y-2">
            <div className="flex items-center gap-2">
              <CheckCircle2 className="h-5 w-5 text-emerald-500 animate-[fadeInUp_0.8s_ease-out_forwards]" />
              <h3 className="text-lg font-semibold">Performance Tracking</h3>
            </div>
            <p className="text-sm sm:text-base text-muted-foreground leading-relaxed">
              Portfolio equity includes cash, the market value of open positions, and unrealized P&amp;L. Every
              entry and exit is logged, and drawdowns are recorded as they occur. There are no hidden resets,
              no curve smoothing, and no removal of losing periods. What you see in the equity curve is the
              full path the portfolio actually took.
            </p>
          </section>

          {/* Section E */}
          <section className="space-y-3">
            <div className="flex items-center gap-2">
              <CheckCircle2 className="h-5 w-5 text-emerald-500 animate-[fadeInUp_0.9s_ease-out_forwards]" />
              <h3 className="text-lg font-semibold">What We Don&apos;t Do</h3>
            </div>
            <p className="text-sm sm:text-base text-muted-foreground leading-relaxed">
              Marild is designed around risk discipline and auditability. As part of that, there are several practices we deliberately avoid:
            </p>
            <ul className="list-disc pl-5 space-y-1 text-sm sm:text-base text-muted-foreground">
              <li>No martingale or doubling-down position sizing.</li>
              <li>No stacking unrelated signals into the same ticker.</li>
              <li>No hindsight parameter tuning to fit past data.</li>
              <li>No deleting or hiding losing trades from the history.</li>
            </ul>
          </section>

          <section className="pt-2">
            <Badge variant="outline" className="border-emerald-500/40 bg-emerald-500/5 text-xs text-emerald-700 dark:text-emerald-400">
              Transparency is a feature, not a marketing claim.
            </Badge>
          </section>
        </div>

        <DialogFooter className="mt-4 flex flex-col sm:flex-row sm:justify-between sm:items-center gap-3">
          <p className="text-xs sm:text-sm text-muted-foreground sm:text-left text-center">
            These rules apply to every model portfolio so that performance can be compared, audited, and
            improved over time.
          </p>
          <Link href={performanceHref} className="sm:self-end w-full sm:w-auto" prefetch={false}>
            <Button variant="outline" className="w-full sm:w-auto gap-2 text-sm">
              View Live Performance
              <ArrowRight className="h-4 w-4" />
            </Button>
          </Link>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
