"use client";

import { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";

import {
  Dialog,
  DialogTrigger,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
} from "@/components/ui/dialog";

import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import {
  Info,
  Zap,
  ShieldCheck,
  Layers,
  ClipboardList,
  Clock,
  LineChart,
  RefreshCw,
  ChevronDown,
  ChevronUp,
} from "lucide-react";


type AnimatedSectionProps = {
  title: string;
  icon: React.ComponentType<React.SVGProps<SVGSVGElement>>;
  color: string;
  children: React.ReactNode;
};

// Reusable collapsible animated section
function AnimatedSection({ title, icon: Icon, color, children }: AnimatedSectionProps) {
  const [open, setOpen] = useState(false);

  return (
    <div className="border rounded-xl p-4 bg-neutral-50 dark:bg-neutral-900 transition-all">
      <button
        type="button"
        className="w-full flex items-center justify-between"
        onClick={() => setOpen((prev) => !prev)}
        aria-expanded={open}
      >
        <div className="flex items-center gap-2 text-left">
          <Icon className={`w-5 h-5 ${color}`} />
          <span className="font-semibold">{title}</span>
        </div>

        {open ? (
          <ChevronUp className="w-4 h-4 opacity-50" />
        ) : (
          <ChevronDown className="w-4 h-4 opacity-50" />
        )}
      </button>

      <AnimatePresence initial={false}>
        {open && (
          <motion.div
            key="content"
            initial={{ opacity: 0, height: 0, marginTop: 0 }}
            animate={{ opacity: 1, height: "auto", marginTop: 12 }}
            exit={{ opacity: 0, height: 0, marginTop: 0 }}
            transition={{ duration: 0.25 }}
            className="text-sm text-muted-foreground leading-relaxed overflow-hidden"
          >
            {children}
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}

export default function LiveTradingCriteriaAnimated() {
  return (
    <Card className="border rounded-2xl shadow-md bg-white dark:bg-neutral-900">
      <CardContent className="p-6 flex items-center justify-between gap-4">
        <div className="flex flex-col">
          <h2 className="text-xl font-semibold">How Our AI Trades (Live Mode)</h2>
          <p className="text-sm text-muted-foreground">
            A transparent view of the AI’s real-time trading logic.
          </p>
        </div>

        <Dialog>
          <DialogTrigger asChild>
            <Button variant="outline" size="sm" className="flex items-center gap-2">
              <Info className="w-4 h-4" />
              View Criteria
            </Button>
          </DialogTrigger>

          <DialogContent className="max-w-2xl max-h-[85vh] overflow-y-auto rounded-xl">
            <DialogHeader>
              <DialogTitle className="text-2xl font-bold">
                Live Trading Execution Rules
              </DialogTitle>
              <DialogDescription>
                These sections outline exactly how the AI opens, sizes, and manages live trades.
              </DialogDescription>
            </DialogHeader>

            <div className="space-y-4 mt-4">
              {/* Section 1: Signal quality */}
              <AnimatedSection
                title="High-Confidence AI Signals Only"
                icon={Zap}
                color="text-blue-500"
              >
                <p>
                  The live portfolios only trade signals with
                  <span className="font-medium"> confidence ≥ 60</span>. These signals are
                  generated by the same AI engine that powers the Discord alerts, but can
                  also include valid trades that don’t pass the stricter Discord
                  publishing filters (higher confidence thresholds and daily caps).
                </p>
              </AnimatedSection>

              {/* Section 2: Position sizing */}
              <AnimatedSection
                title="Risk-Based Position Sizing"
                icon={ShieldCheck}
                color="text-green-500"
              >
                <ul className="ml-4 list-disc space-y-1">
                  <li>
                    Daytrade portfolio: {""}
                    <span className="font-medium">1% of equity at risk per trade</span>
                  </li>
                  <li>
                    Swing portfolio: {""}
                    <span className="font-medium">0.75% of equity at risk per trade</span>
                  </li>
                  <li>
                    Minimum size: <span className="font-medium">$1,000</span> notional per trade
                  </li>
                  <li>
                    Size is based on the distance between {""}
                    <span className="font-medium">entry and stop-loss</span>, so more volatile
                    setups automatically get smaller share size.
                  </li>
                </ul>
              </AnimatedSection>

              {/* Section 3: Portfolio limits */}
              <AnimatedSection
                title="Strict Portfolio Risk Limits"
                icon={Layers}
                color="text-purple-500"
              >
                <ul className="ml-4 list-disc space-y-1">
                  <li>
                    Max <span className="font-medium">80%</span> of each portfolio can be
                    allocated at any time (20% always kept in cash).
                  </li>
                  <li>
                    Max <span className="font-medium">10 Swing positions</span> open at once.
                  </li>
                  <li>
                    Max concurrent Daytrader positions according to engine configuration
                    (e.g. 3 intraday trades at a time).
                  </li>
                  <li>
                    <span className="font-medium">No duplicate positions</span> in the same
                    ticker for the same strategy (one Daytrade and one Swing can coexist, but
                    not two Swings in the same symbol).
                  </li>
                </ul>
              </AnimatedSection>

              {/* Section 4: Trade management */}
              <AnimatedSection
                title="Trade Management & Exit Rules"
                icon={ClipboardList}
                color="text-orange-500"
              >
                <ul className="ml-4 list-disc space-y-1">
                  <li>
                    Every trade has a predefined {""}
                    <span className="font-medium">entry, stop-loss, and take-profit</span>{" "}
                    from the AI signal.
                  </li>
                  <li>
                    Positions are re-priced using live market data and marked-to-market P&amp;L
                    on a fixed schedule.
                  </li>
                  <li>
                    Exits are classified as {""}
                    <span className="font-medium">take-profit hit, stop-loss hit, or
                    end-of-day flatten</span> (for intraday strategies).
                  </li>
                </ul>
              </AnimatedSection>

              {/* Section 5: Daytrader EOD */}
              <AnimatedSection
                title="Daytrader Positions Auto-Close Daily"
                icon={Clock}
                color="text-red-500"
              >
                <p>
                  All intraday Daytrader positions are closed at {""}
                  <span className="font-medium">20:55 UTC (4:55 PM ET)</span>{" "}
                  to avoid overnight exposure. No Daytrader trade is held past the cash
                  session close.
                </p>
              </AnimatedSection>

              {/* Section 6: Portfolios */}
              <AnimatedSection
                title="Two Independent Portfolios"
                icon={LineChart}
                color="text-indigo-500"
              >
                <ul className="ml-4 list-disc space-y-1">
                  <li>
                    <span className="font-medium">Daytrade portfolio</span>  ultra-short-term
                    trades, intraday only.
                  </li>
                  <li>
                    <span className="font-medium">Swing portfolio</span>  multi-day strategic
                    trades based on 4h structures.
                  </li>
                  <li>
                    Each portfolio runs with a dedicated {""}
                    <span className="font-medium">$100,000 starting equity</span>
                    and tracks its own equity curve.
                  </li>
                </ul>
              </AnimatedSection>

              {/* Section 7: Update frequency */}
              <AnimatedSection
                title="Updated Every 5 Minutes"
                icon={RefreshCw}
                color="text-teal-500"
              >
                <p>
                  Every <span className="font-medium">5 minutes</span> the system:
                </p>
                <ul className="ml-4 list-disc space-y-1 mt-1">
                  <li>Checks for fresh high-confidence AI signals.</li>
                  <li>Updates all open positions with the latest prices and P&amp;L.</li>
                  <li>Saves a new portfolio snapshot for the live equity curve.</li>
                  <li>Syncs changes to the live trade log and dashboard.</li>
                </ul>
              </AnimatedSection>
            </div>
          </DialogContent>
        </Dialog>
      </CardContent>
    </Card>
  );
}
