'use client';

import { Card, CardContent } from '@/components/ui/card';
import { Tooltip, TooltipTrigger, TooltipContent } from '@/components/ui/tooltip';
import { Wallet, TrendingUp, CheckCircle, BarChart3, HelpCircle } from 'lucide-react';

interface PerformanceSummary {
  starting_equity: number;
  current_equity: number;
  total_return_pct: number;
  trades_count: number;
  win_rate_pct: number;
}

interface StatsGridProps {
  summary: PerformanceSummary;
}

export default function StatsGrid({ summary }: StatsGridProps) {
  const stats = [
    {
      label: 'Current Equity',
      value: `$${(summary.current_equity / 1000).toFixed(1)}K`,
      subtitle: `Started at $${(summary.starting_equity / 1000).toFixed(0)}K`,
      icon: Wallet,
      iconColor: 'text-blue-600',
      iconBg: 'bg-blue-50',
      tooltip: 'Model portfolio, $100k starting balance. Tracks real-time AI-followed trades only.',
    },
    {
      label: 'Total Return',
      value: `${summary.total_return_pct >= 0 ? '+' : ''}${summary.total_return_pct.toFixed(2)}%`,
      subtitle: `${summary.trades_count} trades`,
      icon: TrendingUp,
      iconColor: summary.total_return_pct >= 0 ? 'text-green-600' : 'text-red-600',
      iconBg: summary.total_return_pct >= 0 ? 'bg-green-50' : 'bg-red-50',
      tooltip: '% return generated by the model portfolio after executing all AI signals.',
    },
    {
      label: 'Win Rate (Closed Trades)',
      value: `${summary.win_rate_pct.toFixed(1)}%`,
      subtitle: `${summary.trades_count} closed trades`,
      icon: CheckCircle,
      iconColor: 'text-green-600',
      iconBg: 'bg-green-50',
      tooltip: 'Percentage of closed trades with positive P&L.',
    },
  ];

  return (
    <div>
      <h2 className="text-xl font-semibold text-gray-900 mb-4">Performance Metrics</h2>
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
        {stats.map((stat) => {
          const Icon = stat.icon;
          return (
            <Card key={stat.label} className="border-gray-200">
              <CardContent className="pt-6">
                <div className="flex items-start justify-between mb-3">
                  <div className="flex-1">
                    <div className="flex items-center gap-1">
                      <p className="text-sm font-medium text-gray-600 mb-1">
                        {stat.label}
                      </p>
                      <Tooltip>
                        <TooltipTrigger asChild>
                          <button className="inline-flex items-center justify-center">
                            <HelpCircle className="w-3.5 h-3.5 text-gray-400 hover:text-gray-600 transition-colors" />
                          </button>
                        </TooltipTrigger>
                        <TooltipContent className="max-w-[250px] text-sm">
                          {stat.tooltip}
                        </TooltipContent>
                      </Tooltip>
                    </div>
                  </div>
                  <div className={`p-2 rounded-lg ${stat.iconBg}`}>
                    <Icon className={`w-5 h-5 ${stat.iconColor}`} />
                  </div>
                </div>
                <div className="space-y-1">
                  <p className="text-2xl font-bold text-gray-900">
                    {stat.value}
                  </p>
                  <p className="text-xs text-gray-500">
                    {stat.subtitle}
                  </p>
                </div>
              </CardContent>
            </Card>
          );
        })}
      </div>
    </div>
  );
}
